version: '3.7'

services: 
    user-service:
        image: quoctoanphamtoan/msav1-user-service:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports: 
            - "8001:8001"
        # networks: 
        #     - user-post-network
        depends_on: 
            - eureka-server
        environment: 
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
        
    post-service:
        image: quoctoanphamtoan/msav1-post-service:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports: 
            - "8002:8002"
        # networks: 
        #     - user-post-network
        depends_on: 
            - eureka-server
        environment: 
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
        
        
    eureka-server:
        image: quoctoanphamtoan/msav1-eureka-server:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports: 
            - "8761:8761"

    api-gateway:
        image: quoctoanphamtoan/msav1-api-gateway:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports: 
            - "8765:8765"
        depends_on: 
            - eureka-server
        environment: 
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
          
    
networks: 
    user-post-network:            